### ISSUE TITLE
[DISCUSS]: PLR0913 ("too many arguments")

### ISSUE THREAD

**Issue by lengau** [canonical/starbase#133]
https://docs.astral.sh/ruff/rules/too-many-arguments/

Currently we limit methods to 5 arguments (the default), but we've ended up with many places where this is insufficient.

I'd like opinions on whether we should change the default here and if so, what to. 

[Snapcraft has several pylint configurations](https://github.com/snapcore/snapcraft/blob/5fc76d839998ab8e86a925598d77054d669a37df/pyproject.toml#L31) we may want to override, including setting max args to 6. Is this reasonable, or should we bump to, say, 8? There are trade-offs in each direction.

cc @syu-w @mr-cal @tigarmo @cmatsuoka @sergiusens for conversation.

**Comment by mr-cal** [comment]
I think anywhere from 6 to 8 is OK as a default.  

I wish ruff would let us set the max arguments for `__init__()`s separate from all other functions, as there are many `__init__()`s in our libraries where this can't be avoided and shouldn't count as a code smell.

**Comment by lengau** [comment]
I agree with @mr-cal on `__init__`. I'd even be okay with entirely disabling PLR0913 for `__init__` methods since we generally can't do anything about it for them.

**Comment by lengau** [comment]
Per in-person conversation, we're choosing 8
